### PR TITLE
For #! use /usr/bin/env to find bash

### PR DESCRIPTION
**Pull request by e40**
so it works on macOS.

Very cool project!  I love BASH and always enjoy novel uses!

### CODE REVIEW

**Comment by izabera** [comment]
just wondering, does it work ok on macos?  in iterm2 i'm assuming?

**Comment by e40** [comment]
> just wondering, does it work ok on macos? in iterm2 i'm assuming?

It worked in Terminal.  Don't have iterm2.

**Comment by e40** [comment]
> just wondering, does it work ok on macos? in iterm2 i'm assuming?

Btw, I use Homebrew BASH.

**Comment by izabera** [comment]
neat, thanks.  let's merge this

**Pull request merged**
